const greetings = [
	"Beautiful world!",
	"Hello there!",
	"What a wonderful day!",
	"You're doing great!",
	"Keep shining!",
	"Have a fantastic day!",
	"You're amazing!",
	"It's a beautiful day!",
	"Smile, it's contagious!",
	"You're on the right track!",
	"Keep pushing forward!",
	"Every day is a new chance!",
	"You got this!",
	"Believe in yourself!",
	"You're stronger than you think!",
	"Don't give up!",
	"You're doing your best!",
	"That's all that matters!",
	"Keep going, you're almost there!",
	"You're making progress!",
	"Don't forget to breathe!",
	"You're doing great, keep it up!",
	"You're on the path to success!",
	"You're capable of anything!",
	"You're unstoppable!",
	"Welcome back!",
	"Hello there!",
	"Good to see you!",
	"Hi, darling!",
	"Hey, super girlfriend!",
	"Howdy!",
	"What’s up?",
	"Nice to meet you!",
	"Let's get started!",
	"Ready to explore?",
	"Hi, awesome!",
	"Feeling great?",
	"You’re amazing!",
	"Ready for today?",
	"Hey, champ!",
	"Welcome aboard!",
	"Hi, there!",
	"Let’s go!",
	"Happy to see you!",
];

export const randomGreeting =
	greetings[Math.floor(Math.random() * greetings.length)];

export default greetings;
