// This file is generated by npm run build:icons

export type IconName =
	| "bookmark-filled"
	| "bookmark-outline"
	| "copy-outline"
	| "eye-outline"
	| "filter-outline"
	| "heart-filled"
	| "heart-outline"
	| "insert-outline"
	| "magnifer-outline"
	| "menu-dots-outline"
	| "pen-outline"
	| "square-share-line-outline"
	| "trash-outline"
	| "user-outline";
