import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { TRPCReactProvider } from "@/trpc/react";
import { NextUIProvider } from "@nextui-org/react";

export const metadata: Metadata = {
  title: "Stories of us",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <TRPCReactProvider>
          <AntdRegistry>
            <NextUIProvider>{children}</NextUIProvider>
          </AntdRegistry>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
