const ANIMATION_SCALE_KEYFRAMES = [1, 1.2, 1];
const ANIMATION_DURATION = 0.5;
const ANIMATION_TIMES = [0, 0.5, 1];
const ICON_SIZE_SMALL = "w-4 h-4";
const ICON_SIZE_MEDIUM = "w-5 h-5";
const ICON_SIZE_LARGE = "w-6 h-6";
const DELETE_CONFIRMATION_MESSAGE =
  "Are you sure you want to delete this story?";

// Gradient Classes Configuration
const gradientClasses = {
  purple: "bg-gradient-to-b from-[#E4D6F5]/50 to-transparent",
  blue: "bg-gradient-to-b from-[#A1C9F2]/50 to-transparent",
  violet: "bg-gradient-to-b from-[#C5A3F2]/50 to-transparent",
  green: "bg-gradient-to-b from-[#C6F6D5]/50 to-transparent",
  orange: "bg-gradient-to-b from-[#FFD6A5]/50 to-transparent",
  red: "bg-gradient-to-b from-[#FFA9A9]/50 to-transparent",
  yellow: "bg-gradient-to-b from-[#FFFACD]/50 to-transparent",
  teal: "bg-gradient-to-b from-[#A7F3D0]/50 to-transparent",
  pink: "bg-gradient-to-b from-[#F9A8D4]/50 to-transparent",
  indigo: "bg-gradient-to-b from-[#A5F3FC]/50 to-transparent",
  cyan: "bg-gradient-to-b from-[#A5F3FC]/50 to-transparent",
  lime: "bg-gradient-to-b from-[#D8F5A2]/50 to-transparent",
  emerald: "bg-gradient-to-b from-[#6EE7B7]/50 to-transparent",
  amber: "bg-gradient-to-b from-[#F6E05E]/50 to-transparent",
  brown: "bg-gradient-to-b from-[#F5DEB3]/50 to-transparent",
  gold: "bg-gradient-to-b from-[#FFD700]/50 to-transparent",
  bronze: "bg-gradient-to-b from-[#CD7F32]/50 to-transparent",
  copper: "bg-gradient-to-b from-[#FFC400]/50 to-transparent",
  mint: "bg-gradient-to-b from-[#ACFFAC]/50 to-transparent",
  lavender: "bg-gradient-to-b from-[#C7B8EA]/50 to-transparent",
  peach: "bg-gradient-to-b from-[#FFD7BE]/50 to-transparent",
  magenta: "bg-gradient-to-b from-[#FF00FF]/50 to-transparent",
  turquoise: "bg-gradient-to-b from-[#00BFFF]/50 to-transparent",
  coral: "bg-gradient-to-b from-[#FFC67D]/50 to-transparent",
  salmon: "bg-gradient-to-b from-[#FFA07A]/50 to-transparent",
  limegreen: "bg-gradient-to-b from-[#32CD32]/50 to-transparent",
  forestgreen: "bg-gradient-to-b from-[#228B22]/50 to-transparent",
  darkgreen: "bg-gradient-to-b from-[#008080]/50 to-transparent",
  lightgreen: "bg-gradient-to-b from-[#90EE90]/50 to-transparent",
  palegreen: "bg-gradient-to-b from-[#98FB98]/50 to-transparent",
  seagreen: "bg-gradient-to-b from-[#20B2AA]/50 to-transparent",
  darkseagreen: "bg-gradient-to-b from-[#8FBC8F]/50 to-transparent",
  mediumseagreen: "bg-gradient-to-b from-[#3CB371]/50 to-transparent",
  lightseagreen: "bg-gradient-to-b from-[#20B2AA]/50 to-transparent",
  paleseagreen: "bg-gradient-to-b from-[#AFEEEE]/50 to-transparent",
  sienna: "bg-gradient-to-b from-[#A0522D]/50 to-transparent",
  skyblue: "bg-gradient-to-b from-[#87CEEB]/50 to-transparent",
  slateblue: "bg-gradient-to-b from-[#6A5ACD]/50 to-transparent",
  slategray: "bg-gradient-to-b from-[#708090]/50 to-transparent",
  springgreen: "bg-gradient-to-b from-[#00FF7F]/50 to-transparent",
  steelblue: "bg-gradient-to-b from-[#4682B4]/50 to-transparent",
  tan: "bg-gradient-to-b from-[#D2B48C]/50 to-transparent",
  thistle: "bg-gradient-to-b from-[#D8BFD8]/50 to-transparent",
  tomato: "bg-gradient-to-b from-[#FF6347]/50 to-transparent",
} as const;

const BEAR_STORES = [
  {
    name: "Vincom Center Bà Triệu",
    address: "191 Bà Triệu, Hai Bà Trưng, Hà Nội, Việt Nam",
    latitude: 21.011301,
    longitude: 105.849396,
    notes: "TTTM lớn, có khu gắp thú bông.",
    openingHours: "09:30 - 22:00",
    rating: 4.5,
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    ],
    tags: ["Shopping", "Wifi", "Parking"],
    price: 3,
    amenities: ["Wifi", "Parking", "AC"],
    popularity: 85,
  },
  {
    name: "Vincom Mega Mall Times City",
    address: "458 Minh Khai, Hai Bà Trưng, Hà Nội, Việt Nam",
    latitude: 21.026,
    longitude: 105.87,
    notes: "Khu thương mại với nhiều máy gắp.",
    openingHours: "09:30 - 22:00",
    rating: 4.7,
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    ],
    tags: ["Shopping", "Entertainment", "Parking"],
    price: 3,
    amenities: ["Wifi", "Parking", "AC", "Food Court"],
    popularity: 92,
  },
  {
    name: "AEON Mall Long Biên",
    address: "27 Cổ Linh, Long Biên, Hà Nội, Việt Nam",
    latitude: 21.055,
    longitude: 105.893,
    notes: "Mall lớn, khu giải trí Dream Games.",
    openingHours: "10:00 - 22:00",
    rating: 4.8,
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    ],
    tags: ["Shopping", "Entertainment", "Parking", "Wifi"],
    price: 2,
    amenities: ["Wifi", "Parking", "AC", "Food Court", "Cinema"],
    popularity: 95,
  },
  {
    name: "Royal City (Vincom Mega Mall Royal City)",
    address: "72A Nguyễn Trãi, Thanh Xuân, Hà Nội, Việt Nam",
    latitude: 21.0045,
    longitude: 105.816,
    notes: "Trung tâm thương mại + khu vui chơi; máy gắp thú.",
    openingHours: "09:30 - 22:00",
    rating: 4.6,
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    ],
    tags: ["Shopping", "Entertainment", "Parking"],
    price: 3,
    amenities: ["Wifi", "Parking", "AC", "Ice Rink"],
    popularity: 90,
  },
  {
    name: "The LINC (ParkCity Hanoi)",
    address: "The LINC, KĐT ParkCity Hanoi, La Khê, Hà Đông, Hà Nội, Việt Nam",
    latitude: 20.96566,
    longitude: 105.75671,
    notes: "Khu đô thị + TTTM; chuỗi gắp thú có cơ sở ở đây.",
    openingHours: "09:00 - 21:00",
    rating: 4.4,
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    ],
    tags: ["Shopping", "Park"],
    price: 2,
    amenities: ["Parking", "AC"],
    popularity: 60,
  },
  {
    name: "Vincom Plaza Bắc Từ Liêm",
    address: "234 Phạm Văn Đồng, Cổ Nhuế, Bắc Từ Liêm, Hà Nội, Việt Nam",
    latitude: 21.085,
    longitude: 105.786,
    notes: "TTTM, liệt kê có máy gắp.",
    openingHours: "09:30 - 22:00",
    rating: 4.3,
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    ],
    tags: ["Shopping"],
    price: 2,
    amenities: ["Parking", "AC"],
    popularity: 55,
  },
  {
    name: "Vincom Skylake Phạm Hùng",
    address: "Đường Phạm Hùng, Mỹ Đình 1, Nam Từ Liêm, Hà Nội, Việt Nam",
    latitude: 21.035,
    longitude: 105.781,
    notes: "TTTM, khu giải trí gắp thú.",
    openingHours: "09:30 - 22:00",
    rating: 4.5,
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    ],
    tags: ["Shopping", "Entertainment"],
    price: 3,
    amenities: ["Parking", "AC", "Cinema"],
    popularity: 70,
  },
  {
    name: "The Garden Shopping Center (The Manor Mỹ Đình)",
    address:
      "Tầng 4, KĐT The Manor Hà Nội, đường Mễ Trì, Mỹ Đình 1, Nam Từ Liêm, Hà Nội, Việt Nam",
    latitude: 21.028,
    longitude: 105.778,
    notes: "Khu gắp thú bông trong TTTM.",
    openingHours: "10:00 - 22:00",
    rating: 4.4,
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    ],
    tags: ["Shopping", "Entertainment"],
    price: 3,
    amenities: ["Parking", "AC"],
    popularity: 65,
  },
  {
    name: "Pick Miu – 188 Bạch Mai",
    address: "188 Bạch Mai, Hai Bà Trưng, Hà Nội, Việt Nam",
    latitude: 21.005,
    longitude: 105.853,
    notes: "Cửa hàng chuyên gắp thú bông và blind-box.",
    openingHours: "09:00 - 23:00",
    rating: 4.9,
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    ],
    tags: ["Entertainment", "Pet Friendly"],
    price: 1,
    amenities: ["Wifi", "AC"],
    popularity: 88,
  },
  {
    name: "The Coffee House – 98 Nguyễn Trãi",
    address: "98 Nguyễn Trãi, Thanh Xuân, Hà Nội, Việt Nam",
    latitude: 20.999,
    longitude: 105.821,
    notes: "Quán cà phê có máy gắp thú bông.",
    openingHours: "07:00 - 22:30",
    rating: 4.2,
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    ],
    tags: ["Cafe", "Wifi"],
    price: 2,
    amenities: ["Wifi", "AC", "Parking"],
    popularity: 75,
  },
  {
    name: "Cộng Cà Phê – 15 Trần Quốc Toản",
    address: "15 Trần Quốc Toản, Hoàn Kiếm, Hà Nội, Việt Nam",
    latitude: 21.028,
    longitude: 105.856,
    notes: "Quán cà phê & máy gắp thú.",
    openingHours: "07:30 - 23:00",
    rating: 4.3,
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    ],
    tags: ["Cafe", "Wifi"],
    price: 2,
    amenities: ["Wifi", "AC"],
    popularity: 78,
  },
  {
    name: "Highlands Coffee – 27 Huỳnh Thúc Kháng",
    address: "27 Huỳnh Thúc Kháng, Đống Đa, Hà Nội, Việt Nam",
    latitude: 21.025,
    longitude: 105.837,
    notes: "Chi nhánh có máy gắp thú bông được liệt kê.",
    openingHours: "07:00 - 23:00",
    rating: 4.1,
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    ],
    tags: ["Cafe", "Wifi"],
    price: 2,
    amenities: ["Wifi", "AC", "Parking"],
    popularity: 72,
  },
  {
    name: "Pick Me – Tầng 5 Tràng Tiền Plaza",
    address:
      "Tầng 5, Tràng Tiền Plaza, 24-26 Tràng Tiền, Hoàn Kiếm, Hà Nội, Việt Nam",
    latitude: 21.0285,
    longitude: 105.854,
    notes: "Chuỗi Pick Me (máy gắp thú) tại mall hạng sang.",
    openingHours: "09:30 - 21:30",
    rating: 4.6,
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    ],
    tags: ["Entertainment", "Shopping"],
    price: 4,
    amenities: ["AC", "Parking"],
    popularity: 80,
  },
  {
    name: "Tiệm gắp thú Momo – Hàng Bông",
    address: "Số 1 phố Tống Duy Tân, Hàng Bông, Hoàn Kiếm, Hà Nội, Việt Nam",
    latitude: 21.033,
    longitude: 105.853,
    notes: "Tiệm gắp thú bông nhỏ; ghi trong FB.",
    openingHours: "10:00 - 22:00",
    rating: 4.5,
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    ],
    tags: ["Entertainment"],
    price: 1,
    amenities: ["AC"],
    popularity: 50,
  },
  {
    name: "Gắp gấu 5K – Vincom Mega Mall Times City",
    address: "458 Minh Khai, Hai Bà Trưng, Hà Nội, Việt Nam",
    latitude: 21.026,
    longitude: 105.87,
    notes: "Phụ mục trong Times City; thương hiệu gắp thú giá hợp lý.",
    openingHours: "09:30 - 22:00",
    rating: 4.4,
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    ],
    tags: ["Entertainment", "Shopping"],
    price: 1,
    amenities: ["AC", "Parking"],
    popularity: 85,
  },
  {
    name: "Khu vui chơi – Công viên Thống Nhất",
    address: "216 Trần Quang Hải, Hai Bà Trưng, Hà Nội, Việt Nam",
    latitude: 21.026,
    longitude: 105.847,
    notes: "Công viên liệt kê có máy gắp thú bông.",
    openingHours: "06:00 - 22:00",
    rating: 4.0,
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    ],
    tags: ["Park", "Entertainment"],
    price: 1,
    amenities: ["Parking"],
    popularity: 60,
  },
  {
    name: "Khu vui chơi – Công viên Lê Nin",
    address: "1 Lê Nin, Hoàn Kiếm, Hà Nội, Việt Nam",
    latitude: 21.028,
    longitude: 105.835,
    notes: "Công viên có khu máy gắp thú bông.",
    openingHours: "06:00 - 22:00",
    rating: 4.0,
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    ],
    tags: ["Park", "Entertainment"],
    price: 1,
    amenities: ["Parking"],
    popularity: 55,
  },
  {
    name: "Khu vui chơi – Công viên Hồ Tây",
    address: "614 Lạc Long Quân, Tây Hồ, Hà Nội, Việt Nam",
    latitude: 21.056,
    longitude: 105.822,
    notes: "Công viên + khu giải trí; được liệt kê trong bài viết.",
    openingHours: "08:00 - 20:00",
    rating: 4.3,
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    ],
    tags: ["Park", "Entertainment"],
    price: 2,
    amenities: ["Parking"],
    popularity: 70,
  },
  {
    name: "Pick Now – 242 Thượng Đình",
    address: "242 Thượng Đình, Thanh Xuân, Hà Nội, Việt Nam",
    latitude: 20.999,
    longitude: 105.82,
    notes: "Tiệm gắp thú bông chuyên nghiệp.",
    openingHours: "09:00 - 22:00",
    rating: 4.7,
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    ],
    tags: ["Entertainment"],
    price: 2,
    amenities: ["AC", "Wifi"],
    popularity: 82,
  },
  {
    name: "Tiệm gắp thú nhỏ – Chi nhánh nào đó",
    address: "Số 5A Lương Ngọc Quyến, Hoàn Kiếm, Hà Nội, Việt Nam",
    latitude: 21.028,
    longitude: 105.853,
    notes: "Cửa hàng gắp thú bông liệt kê tại bài viết.",
    openingHours: "10:00 - 22:00",
    rating: 4.2,
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    ],
    tags: ["Entertainment"],
    price: 1,
    amenities: ["AC"],
    popularity: 40,
  },
];

export {
  ANIMATION_SCALE_KEYFRAMES,
  ANIMATION_DURATION,
  ANIMATION_TIMES,
  ICON_SIZE_SMALL,
  ICON_SIZE_MEDIUM,
  ICON_SIZE_LARGE,
  DELETE_CONFIRMATION_MESSAGE,
  gradientClasses,
  BEAR_STORES,
};
